<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'session' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\http-foundation\\Session\\SessionInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-foundation\\Session\\Session.php';

return $this->services['session'] = new \Symfony\Component\HttpFoundation\Session\Session(${($_ = isset($this->services['session.storage.native']) ? $this->services['session.storage.native'] : $this->load('getSession_Storage_NativeService.php')) && false ?: '_'});
